NAME:Amishi Gupta
Roll No. 23/CS/048

In [1]:
import torch
import numpy as np

In [7]:
#1D tensor
t1 = torch.tensor([1, 2, 3])
print("1D:\n",t1)

#2D tensor
t2 = torch.tensor([[1, 2, 3],[4, 5, 6]])
print("\n2D:\n",t2)

#3D tensor
t3 = torch.randn(2, 2, 3)
print("\n3D:\n",t3)


1D:
 tensor([1, 2, 3])

2D:
 tensor([[1, 2, 3],
        [4, 5, 6]])

3D:
 tensor([[[-0.4520,  0.9471, -1.1955],
         [ 0.8330, -1.2734, -2.1747]],

        [[-0.1100, -1.9184, -0.7544],
         [-0.5672,  0.9234,  1.0973]]])


In [8]:
#basic operations
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print("Add:",a + b)
print("Subtract:",a-b)
print("Multiply:",a*b)
print("Divide:",a/b)


Add: tensor([5, 7, 9])
Subtract: tensor([-3, -3, -3])
Multiply: tensor([ 4, 10, 18])
Divide: tensor([0.2500, 0.4000, 0.5000])


In [9]:
#indexing and slicing
x = torch.tensor([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print("First row:",x[0])
print("Column 1:",x[:,1])
print("Slice rows 0-1 and cols 1-2:\n", x[0:2,1:3])


First row: tensor([10, 20, 30])
Column 1: tensor([20, 50, 80])
Slice rows 0-1 and cols 1-2:
 tensor([[20, 30],
        [50, 60]])


In [10]:
#boolean masking
y = torch.tensor([1, 4, 7, 2, 9, 3])
mask = y > 3
print("Mask:",mask)
print("Values>3:", y[mask])


Mask: tensor([False,  True,  True, False,  True, False])
Values>3: tensor([4, 7, 9])


In [11]:
#extracting subtensors
matrix = torch.arange(1, 17).reshape(4, 4)
print("Original:\n", matrix)
print("\nTop left 2x2:\n",matrix[:2, :2])
print("\nBottom row:\n",matrix[-1])


Original:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Top left 2x2:
 tensor([[1, 2],
        [5, 6]])

Bottom row:
 tensor([13, 14, 15, 16])


In [12]:
#functions
t = torch.arange(1, 7)
print("Original:",t)

#reshape
print("Reshape to 2x3:\n", t.reshape(2, 3))

#view
print("View to 3x2:\n", t.view(3, 2))

# unsqueeze
print("Unsqueeze(add dim at 0):", t.unsqueeze(0))
print("Unsqueeze(add dim at 1):", t.unsqueeze(1))

#squeeze
ts = torch.tensor([[1, 2, 3]])
print("Squeeze:", ts.squeeze())


Original: tensor([1, 2, 3, 4, 5, 6])
Reshape to 2x3:
 tensor([[1, 2, 3],
        [4, 5, 6]])
View to 3x2:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
Unsqueeze(add dim at 0): tensor([[1, 2, 3, 4, 5, 6]])
Unsqueeze(add dim at 1): tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
Squeeze: tensor([1, 2, 3])


In [16]:
#comparing .reshape()
arr = np.arange(1, 7)
print("NumPy reshape:\n", arr.reshape(2, 3))
ten = torch.arange(1, 7)
print("PyTorch reshape:\n", ten.reshape(2, 3))


NumPy reshape:
 [[1 2 3]
 [4 5 6]]
PyTorch reshape:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
#broadcasting
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([10, 20, 30])
print("Broadcasted result:\n",A+b)


Broadcasted result:
 tensor([[11, 22, 33],
        [14, 25, 36]])


In [15]:
#in place vs out of place operations
a = torch.tensor([1, 2, 3])
b = a + 5
print("Original:", a)
print("New:", b)


Original: tensor([1, 2, 3])
New: tensor([6, 7, 8])
